name: Build Infra
on:
  workflow_call:
    inputs:
      AWSSUB:
        description: AWS Subscription
        required: true
        type: string
permissions:
  id-token: write
  contents: read
  actions: read
  deployments: read
env:
   TERRAFORM_PATH: 'terraform'
jobs:
  deploy-terraform:
    name: Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:        
      - name: "Checkout Lambda Repository"
        uses: actions/checkout@v2
        with:
          repository: chegireddy/GHActions
          ref: main
          path: GHActions_local
      - name: TFC AWS Provider Setup 
        run: |
          ls -lart
          ls -lart
      - name: zipping the files
        run: |
          #zip -r python.zip -x ${{ env.TERRAFORM_PATH }}/GHActions_local/
          cd GHActions_local
          ls -lart
          zip -r "python1.zip -x GHActions_local/* .
          #zip -r "test.zip" -x "test.txt"
