name: Build Infra
on:
  workflow_call:
    inputs:
      AWSSUB:
        description: AWS Subscription
        required: true
        type: string
permissions:
  id-token: write
  contents: read
  actions: read
  deployments: read
env:
   TERRAFORM_PATH: 'terraform'
jobs:
  deploy-terraform:
    name: Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:        
      - name: "Checkout Lambda Repository"
        uses: actions/checkout@v2
        with:
          repository: chegireddy/GHActions
          ref: main
          path: edt_asg_lambdas
      - name: TFC AWS Provider Setup 
        shell: bash
        run: |
          ls -lart
          ls -lart
      - name: zipping the files
        shell: bash
        run: |
          #zip -r python.zip -x ${{ env.TERRAFORM_PATH }}/GHActions_local/
          cd edt_asg_lambdas
          zip -vr uie_uie_python.zip python
          ls -lart
          #zip -r test.zip -x .\GHActions_local\
          #zip -r "test.zip" -x "test.txt"
