name: Build Infra
on:
  workflow_call:
    inputs:
      AWSSUB:
        description: AWS Subscription
        required: true
        type: string
permissions:
  id-token: write
  contents: read
  actions: read
  deployments: read
env:
   TERRAFORM_PATH: 'test'
jobs:
  deploy-terraform:
    name: Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: VG
    steps:        
      - name: "Checkout Lambda Repository"
        uses: actions/checkout@v2
        with:
          repository: GHActions
          ref: main
          path: /home/runner/work/GHActions/GHActions/VG/
      #- name: TFC AWS Provider Setup 
        #shell: bash
        #run: |
          #ls -lart
          #ls -lart
      - name: zipping the files
        shell: bash
        run: |
          #zip -r python.zip -x ${{ env.TERRAFORM_PATH }}/GHActions_local/
          cd GHActions_local
          zip -vr ../GHActions_local*
          ls -lart
          #zip -r test.zip -x .\GHActions_local\
          #zip -r "test.zip" -x "test.txt"
