name: Build Infra
on:
  workflow_call:
    inputs:
      AWSSUB:
        description: AWS Subscription
        required: true
        type: string
permissions:
  id-token: write
  contents: read
  actions: read
  deployments: read
env:
   TERRAFORM_PATH: 'terraform'
jobs:
  deploy-terraform:
    name: Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:        
      - name: "Checkout Lambda Repository"
        uses: actions/checkout@v2
        with:
          repository: chegireddy/GHActions
          ref: main
          path: ${{ env.TERRAFORM_PATH }}/GHActions_local
      - name: TFC AWS Provider Setup 
        run: |
          ls -lart
          cd GHActions_local
          ls -lart
